### ISSUE TITLE
建议：YCShadowView 的方法名没必要加前缀

### ISSUE THREAD

**Issue by ElfSundae** [YotrolZ/YCShadowView#1]
YCShadowView 是 UIView 的子类，不是 UIView 的 category ，没必要给方法名加前缀 `yc_`

https://github.com/YotrolZ/YCShadowView/blob/4f88e012e025645058e9d58815b05b3f4660f2de/YCShadowView/Classes/YCShadowView.h#L19-L24

**Comment by YotrolZ** [comment]
感谢回复！
加前缀主要有两个方面的考虑：
1、通过输入”yc_“可以利用xcode的智能提示，能够快速查看YCShadowView的各种方法，方便使用；
2、避免与其他view的方法名的冲突；

**Comment by ElfSundae** [comment]
嗯

**Comment by YotrolZ** [comment]
好的
